[inversionistas]
jfallone = "12345"
agiliberti  = "12345"
ggiliberti = "12345"
mgiliberti = "12345"
mmendez = "12345"
alopez = "12345"
slapi = "12345"
yrendon = "12345"
ydavila = "12345"
cfallone = "12345"
cramirez = "12345"
ffallone = "12345"
