[inversionistas]
gfallone = "gf051975"
agiliberti  = "ag12345"
ggiliberti = "gg12345"
mgiliberti = "mg12345"
mmendez = "mm2405"
alopez = "al9876"
slapi = "sl2025r"
yrendon = "04061710"
ydavila = "2023yd"
cfallone = "cf54321"
cramirez = "critaly2025"
ffallone = "sf08122003"

[archivos_usuarios]
gfallone = "gfallone.xlsx"
agiliberti = "agiliberti.xlsx"
ggiliberti = "ggiliberti.xlsx"
mgiliberti = "mgiliberti.xlsx"
mmendez = "mmendez.xlsx"
alopez = "alopez.xlsx"
slapi = "slapi.xlsx"
yrendon = "yrendon.xlsx"
ydavila = "ydavila.xlsx"
cfallone = "cfallone.xlsx"
cramirez = "cramirez.xlsx"
ffallone = "ffallone.xlsx"
